### ISSUE TITLE
AMAttributedHighlightLabel and Purelayout

### ISSUE THREAD

**Issue by cisnky** [rootd/AMAttributedHighlightLabel#12]
All the resizing works ok, but the clicking of a mention, hashtag or url only works on the first line. I've checked the label background and that is correct the height.

Does AMAttributedHighlightLabel have any known issues with Purelayout?

Thanks in advance.

**Comment by Jellyfishinatrifle** [comment]
I have also found this to be the case when using regular auto layout.... sometimes. If i have a a multi line label, sometimes the links are only tappable in the 1st line, sometimes i can tap a normal piece of text and the linked word will highlight.... its like the touch areas get a bit confused! Any ideas on this? Thanks

**Comment by cisnky** [comment]
@Jellyfishinatrifle I think it had something to do with the parent views height not being set during autolayout.

I was on a tight deadline so I switched to STTweetLabel.
https://github.com/SebastienThiebaud/STTweetLabel

**Comment by Jellyfishinatrifle** [comment]
@cisnky Thanks, Im switching to TTAttributedLabel as I don't think STTweet supports auto layout.

**Comment by rootd** [comment]
Thanks for closing this issue :D
