### ISSUE TITLE
Bad scrolling performance

### ISSUE THREAD

**Issue by rootd** [rootd/AMAttributedHighlightLabel#3]
AMAttributedHighlightLabel has a bad performance when used in a table because the tappable areas get calculated every time the user scrolls. If you don't need tappable links in a table, simply comment out that part.

```
        for(int i = 0;i < matchRange.length;i++)
        {
            CGRect pos = [self rectForLetterAtIndex:matchRange.location + i];
            [touchableWords addObject:tappableWord];
            [touchableWordsRange addObject:[NSValue valueWithRange:matchRange]];
            [touchableLocations addObject:[NSValue valueWithCGRect:pos]];
        }
```

**Comment by JayMehta711** [comment]
Hello every one i am facing problem when i have use  this control in table view it will not give me properly result and not tap # tag in 2 or 3 line if hash tag exist  any solution for that  ?? Please help me. 
![screen shot 2015-03-21 at 12 57 32 pm](https://cloud.githubusercontent.com/assets/6177191/6764176/e69fa46e-cfc9-11e4-9d5d-297ae172b80a.png)
